begin;
create temporary table qa_accounts(id uuid) on commit drop;
insert into qa_accounts select gen_random_uuid() from generate_series(1,3);
insert into auth.users(id) select id from qa_accounts;
select set_config('request.jwt.claim.sub',(select id::text from qa_accounts limit 1),true);
set local role authenticated;
select public.save_private_village('{"version":7,"gold":111}'::jsonb,0,gen_random_uuid(),'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
do $$ begin assert (select count(*)=1 from public.player_saves), 'owner visibility'; end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from qa_accounts offset 1 limit 1),true);
set local role authenticated;
do $$ begin assert (select count(*)=0 from public.player_saves), 'foreign visibility'; end $$;
select public.save_private_village('{"version":7,"gold":222}'::jsonb,0,gen_random_uuid(),'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb');
do $$ begin assert (select count(*)=1 from public.player_saves), 'second owner visibility'; end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from qa_accounts offset 2 limit 1),true);
set local role authenticated;
do $$ begin assert (select count(*)=0 from public.player_saves), 'third foreign visibility'; end $$;
select public.save_private_village('{"version":7,"gold":333}'::jsonb,0,gen_random_uuid(),'cccccccc-cccc-4ccc-8ccc-cccccccccccc');
do $$
declare req uuid:=gen_random_uuid(); result jsonb; rejected boolean;
begin
 assert (select count(*)=1 from public.player_saves), 'third owner visibility';
 result:=public.save_private_village('{"version":7,"gold":334}',1,req,'cccccccc-cccc-4ccc-8ccc-cccccccccccc');
 assert result->>'revision'='2','revision increment';
 result:=public.save_private_village('{"version":7,"gold":334}',1,req,'cccccccc-cccc-4ccc-8ccc-cccccccccccc');
 assert result->>'revision'='2','idempotent retry';
 rejected:=false;
 begin perform public.save_private_village('{"version":7,"gold":999}',1,req,'cccccccc-cccc-4ccc-8ccc-cccccccccccc');
 exception when others then if sqlerrm='request_reused' then rejected:=true; else raise; end if; end;
 assert rejected,'modified retry must fail';
 rejected:=false;
 begin perform public.save_private_village('{"version":7}',1,gen_random_uuid(),'cccccccc-cccc-4ccc-8ccc-cccccccccccc');
 exception when others then if sqlerrm='revision_conflict' then rejected:=true; else raise; end if; end;
 assert rejected,'stale revision must fail';
 rejected:=false;
 begin perform public.save_private_village('{"version":7}',2,gen_random_uuid(),gen_random_uuid());
 exception when others then if sqlerrm='other_device_active' then rejected:=true; else raise; end if; end;
 assert rejected,'other device must fail';
 rejected:=false;
 begin perform public.save_private_village('{}',2,gen_random_uuid(),'cccccccc-cccc-4ccc-8ccc-cccccccccccc');
 exception when others then if sqlerrm='invalid_snapshot' then rejected:=true; else raise; end if; end;
 assert rejected,'missing schema must fail';
 rejected:=false;
 begin update public.player_saves set revision=99;
 exception when insufficient_privilege then rejected:=true; end;
 assert rejected,'direct write must fail';
end $$;
reset role;
select count(*)=3 as three_isolated_test_villages, not has_table_privilege('anon','public.player_saves','select') as anonymous_read_denied, not has_function_privilege('anon','public.save_private_village(jsonb,bigint,uuid,uuid)','execute') as anonymous_write_denied, true as preceding_assertions_passed from public.player_saves where user_id in (select id from qa_accounts);
rollback;
