import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();let checks=0,n=0;
const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222'];
const dev='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',other='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const rid=()=>`00000000-0000-4000-8000-${String(++n).padStart(12,'0')}`;
const check=(x,t)=>{assert.ok(x,t);checks++;};
const reject=async(f,p)=>{await assert.rejects(f,p);checks++;};
const login=async(i,role='authenticated')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i===null?'':ids[i]]);await db.exec(`set role ${role}`);};
const save=async(s,r,id=rid(),d=dev)=>(await db.query('select public.save_private_village($1,$2,$3,$4) result',[s,r,id,d])).rows[0].result;
const hist=async(action='list',target=null,rev=null,id=null,d=null)=>(await db.query('select public.private_save_history($1,$2,$3,$4,$5) result',[action,target,rev,id,d])).rows[0].result;
try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);
 for(const id of ids)await db.query('insert into auth.users values($1)',[id]);
 await db.exec(readFileSync(new URL('../migrations/001_private_saves.sql',import.meta.url),'utf8'));
 await login(0);const baseline={version:7,gold:321,player_name:'Original',unknown_future_field:{keep:true}};const first=rid();await save(baseline,0,first);
 await db.exec('reset role');
 await db.exec(readFileSync(new URL('../../supabase/migrations/20260926215630_private_save_receipts_and_recovery.sql',import.meta.url),'utf8'));
 await login(0);let history=await hist();check(history.versions.length===1&&history.trust==='private_pve','rollout archives existing saves and labels untrusted provenance');
 check((await save(baseline,0,first)).revision===1,'pre-rollout ambiguous request replays');
 const changed={...baseline,gold:400};const next=rid();check((await save(changed,1,next)).revision===2,'ordinary save remains compatible');
 check((await save(baseline,0,first)).revision===1,'old request replays after later successful saves');
 check((await db.query('select snapshot from public.player_saves')).rows[0].snapshot.gold===400,'old replay never overwrites newer progress');
 await reject(()=>save({...baseline,gold:9999},0,first),/request_reused/);
 await reject(()=>save(baseline,0,first,other),/request_reused/);
 await reject(()=>save(baseline,2,rid(),other),/other_device_active/);
 await reject(()=>hist('restore',1,1,rid(),dev),/revision_conflict/);
 await reject(()=>hist('restore',1,2,rid(),other),/other_device_active/);
 await reject(()=>hist('restore',9999,2,rid(),dev),/version_not_found/);
 const restoreId=rid();check((await hist('restore',1,2,restoreId,dev)).revision===3,'restore creates a NEW revision');
 let row=(await db.query('select snapshot from public.player_saves')).rows[0].snapshot;
 assert.deepEqual(row,baseline,'snapshot round trip preserves unknown data exactly');checks++;
 history=await hist();check(history.versions.some(v=>v.revision===2&&v.reason==='before_restore'),'current village backed up before restoration');
 await save({...baseline,gold:500},3);
 check((await hist('restore',1,2,restoreId,dev)).revision===3,'restore lost-response retry replays after later save');
 check((await db.query('select snapshot from public.player_saves')).rows[0].snapshot.gold===500,'restore retry cannot roll back later save');
 await reject(()=>hist('restore',2,4,restoreId,dev),/request_reused/);
 await reject(()=>save(baseline,4,restoreId),/request_reused/);
 await login(1);check((await hist()).versions.length===0,'second account cannot list first account history');
 await save({version:7,gold:1},0);
 await reject(()=>hist('restore',2,1,rid(),dev),/version_not_found/);
 check((await hist()).versions.length===1,'second account gets its own baseline');
 for(const table of ['save_receipts','save_versions'])await reject(()=>db.query(`select * from glutwacht_private.${table}`),/permission denied/);
 await db.exec('reset role');await db.query("update public.player_saves set lease_until=now()-interval '1 second' where user_id=$1",[ids[0]]);
 await login(0);check((await hist('restore',2,4,rid(),other)).revision===5,'device handoff after lease expiration');
 check((await db.query('select snapshot from public.player_saves')).rows[0].snapshot.gold===400,'undo restoration from safety copy');
 for(let i=0;i<52;i++){
  await db.exec('reset role');await db.query("update glutwacht_private.save_versions set created_at=now()-interval '1 hour' where user_id=$1",[ids[0]]);
  await login(0);await save({...baseline,gold:401+i},5+i,rid(),other);
 }
 history=await hist();check(history.versions.length===49&&history.versions.some(v=>v.reason==='baseline'&&v.revision===1),'bounded checkpoints retain immutable baseline');
 check((await save(baseline,0,first)).revision===1,'receipts survive checkpoint pruning');
 await login(null);await reject(()=>hist(),/authentication_required/);
 await login(null,'anon');await reject(()=>hist(),/permission denied/);
 await login(1);await db.exec('reset role');await db.query('delete from auth.users where id=$1',[ids[1]]);await login(1);
 await reject(()=>save({version:7},0),/authentication_required/);
 await reject(()=>hist(),/authentication_required/);
 await db.exec('reset role');
 check((await db.query("select prosecdef from pg_proc where oid='public.private_save_history(text,bigint,bigint,uuid,uuid)'::regprocedure")).rows[0].prosecdef===false,'public RPC is invoker');
 console.log(`SAVE_RECOVERY_SQL_TESTS ${checks}/${checks}`);
}finally{await db.close();}
