import {PGlite} from '@electric-sql/pglite';
import {readFileSync,readdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();let checks=0;
const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333'];
const check=(x,t)=>{assert.ok(x,t);checks++;};
const login=async(i,role='authenticated')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i===null?'':ids[i]]);await db.exec(`set role ${role}`);};
const call=async(action,args={})=>(await db.query('select public.glutwacht_social($1,$2::jsonb) result',[action,JSON.stringify(args)])).rows[0].result;
const reject=async(action,args,pattern)=>{await assert.rejects(()=>call(action,args),pattern);checks++;};
try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);
 for(const id of ids)await db.query('insert into auth.users values($1)',[id]);
 await db.exec(readFileSync(new URL('../migrations/001_private_saves.sql',import.meta.url),'utf8'));
 const dir=new URL('../../supabase/migrations/',import.meta.url);
 await db.exec(readFileSync(new URL(readdirSync(dir).find(x=>x.endsWith('_social_foundation.sql')),dir),'utf8'));
 const tags=[];
 for(let i=0;i<3;i++){
  await login(i);check((await call('state')).enrolled===false,'profile requires opt-in');
  const result=await call('enroll',{name:`Testdorf ${i}`});tags.push(result.me.tag);check(result.me.tag.length===12,'stable unique player tag');
 }
 check(new Set(tags).size===3,'tags differ');
 await login(0);await call('request',{tag:tags[1]});await call('request',{tag:tags[1]});
 check((await call('state')).outgoing.length===1,'duplicate requests are harmless');
 await reject('accept',{tag:tags[1]},/request_not_found/);
 await reject('visit',{tag:tags[1]},/visit_forbidden/);
 await login(2);check((await call('state')).incoming.length===0,'unrelated account cannot see requests');
 await login(1);check((await call('state')).incoming.length===1,'recipient sees request');
 await call('accept',{tag:tags[0]});check((await call('state')).friends.length===1,'recipient can accept');
 await db.exec('reset role');await db.query('insert into public.player_saves(user_id,snapshot) values($1,$2)',[ids[0],{version:7,hall:2,barracks:1,smithy:1,hero:'warrior',gold:987,structures:[{uid:'s1',kind:'lumber',level:1,x:1,z:2,stock:80}],private_secret:'hidden'}]);
 await login(1);let visit=await call('visit',{tag:tags[0]});check(!('gold' in visit.village)&&!('private_secret' in visit.village)&&!('stock' in visit.village.structures[0]),'visit exposes only allowed layout');
 await call('block',{tag:tags[0]});check((await call('state')).friends.length===0,'blocking removes friendship');
 await login(0);await reject('request',{tag:tags[1]},/player_unavailable/);
 await login(1);await call('unblock',{tag:tags[0]});
 await login(0);let state=await call('create_clan',{name:'Glutgarde',description:'Zusammen bauen'});const clan=state.clan.id;
 check(state.clan.role==='owner'&&state.members.length===1,'clan owner created atomically');
 await call('invite',{tag:tags[1]});
 await login(2);await reject('join',{clan_id:clan},/invite_not_found/);
 await login(1);state=await call('join',{clan_id:clan});check(state.members.length===2&&state.clan.role==='member','invited player joins');
 await reject('create_clan',{name:'Zweiter Clan'},/already_in_clan/);
 await reject('promote',{tag:tags[0]},/role_required/);
 await reject('invite',{tag:tags[2]},/role_required/);
 await call('chat',{body:'Hallo Freunde!',request_id:'44444444-4444-4444-8444-444444444444'});
 await call('chat',{body:'Hallo Freunde!',request_id:'44444444-4444-4444-8444-444444444444'});
 await reject('chat',{body:'Zu schnell',request_id:'66666666-6666-4666-8666-666666666666'},/chat_rate_limit/);
 await login(0);state=await call('state');check(state.messages.length===1&&state.messages[0].body==='Hallo Freunde!','clan members see chat');
 await call('report',{tag:tags[1],message_id:state.messages[0].id,reason:'Testmeldung im isolierten Test'});
 check(!('reports' in (await call('state'))),'reports are not exposed to players');
 await call('block',{tag:tags[1]});check((await call('state')).messages.length===0,'blocked messages hidden');await call('unblock',{tag:tags[1]});
 await reject('leave',{},/transfer_first/);
 await call('promote',{tag:tags[1]});
 await login(1);await call('invite',{tag:tags[2]});await reject('kick',{tag:tags[0]},/role_required/);
 await login(2);check((await call('state')).messages.length===0,'outsider cannot read clan messages');await call('join',{clan_id:clan});
 await login(1);await call('kick',{tag:tags[2]});
 await login(2);check((await call('state')).clan===null,'kick removes membership');await reject('chat',{body:'no',request_id:'55555555-5555-4555-8555-555555555555'},/clan_required/);
 await login(0);await call('transfer',{tag:tags[1]});await call('leave');
 await login(1);check((await call('state')).clan.role==='owner','leadership transfer works');await call('leave');check((await call('state')).clan===null,'last owner can leave and delete empty clan');
 await assert.rejects(()=>db.query('select * from glutwacht_private.social_reports'),/permission denied/);checks++;
 await login(null);await reject('state',{},/authentication_required/);
 await login(null,'anon');await reject('state',{},/permission denied/);
 console.log(`SOCIAL_DATABASE_TESTS ${checks}/${checks}`);
}finally{await db.close();}
